Train:
  # YoutubeVOS:
  #   image_dir: path/YTBVOS/train/JPEGImages/
  #   anno: path/YTBVOS/train/Annotations
  #   meta: path/YTBVOS/train/meta.json

  # YoutubeVIS:
  #   image_dir: path/youtubevis/train/JPEGImages/
  #   anno: path/youtubevis/train/Annotations/
  #   meta: path/youtubevis/train/meta.json

  # VIPSeg:
  #   image_dir: path/VIPSeg/VIPSeg_720P/images/
  #   anno: path/VIPSeg/VIPSeg_720P/panomasksRGB/

  # UVO:
  #   train:
  #     image_dir: path/UVO/uvo_frames_sparse
  #     video_json: path/UVO/UVO_sparse_train_video_with_interpolation.json
  #     image_json: path/UVO/UVO_sparse_train_video_with_interpolation_reorg.json
  #   val:
  #     image_dir: path/UVO/uvo_frames_sparse
  #     video_json: path/UVO/VideoSparseSet/UVO_sparse_val_video_with_interpolation.json
  #     image_json: path/UVO/VideoSparseSet/UVO_sparse_val_video_interpolation_reorg.json

  # Mose:
  #   image_dir: path/MOSE/train/JPEGImages/
  #   anno: path/MOSE/train/Annotations/

  MVImageNet:
    txt: ./datasets/Preprocess/mvimagenet.txt  #./datasets/Preprocess/mvimagenet_small.txt
    image_dir: data/MVImgNet_full/

  VitonHD:
    image_dir: data/VitonHD/zalando-hd-resized/train/cloth #path/TryOn/VitonHD/train/cloth/

  # Dresscode:
  #   image_dir: /mnt/workspace/xizhi/data/dresscode/DressCode/upper_body/label_maps/

  # FashionTryon:
  #   image_dir: path/TryOn/FashionTryOn/train

  Lvis:
    image_dir: data/lvis_v1/train2017 
    json_path: data/lvis_v1/lvis_v1_train.json

  # SAM:
  #   sub1: path/SAM/0000
  #   sub2: path/SAM/0001
  #   sub3: path/SAM/0002
  #   sub4: path/SAM/0004

  # Saliency:
  #   MSRA_root: path/Saliency/MSRA10K_Imgs_GT/
  #   TR_root: path/Saliency/DUTS-TR/DUTS-TR-Image/
  #   TE_root: path/Saliency/DUTS-TE/DUTS-TE-Image/
  #   HFlickr_root: path/HFlickr/masks/

Test:
  DreamBooth:
    fg_dir: path/DreamBooth/AnyDoor_DreamBooth
    bg_dir: path/DreamBooth/v1_800

  VitonHDTest:
    image_dir: data/VitonHD/zalando-hd-resized/test/cloth #path/TryOn/VitonHD/test/cloth

  # add lvis
  Lvis:
    image_dir: data/lvis_v1/val2017 
    json_path: data/lvis_v1/lvis_v1_val.json

# for GLIGEN
train_dataset_names: 
  FlickrGrounding:
    which_layer_text: before
    which_layer_image: after_reproject
    image_size: 512
    max_boxes_per_data: 8
    prob_use_caption: 0.5
    random_drop_embedding: both 
    random_crop: False
    random_flip: True

test_dataset_names: 
  FlickrGrounding:
    which_layer_text: before
    which_layer_image: after_reproject
    image_size: 512
    max_boxes_per_data: 8
    prob_use_caption: 1.0
    random_drop_embedding: both 
    random_crop: False
    random_flip: False