pretrained_model: lightning_logs/version_69_text_image_ground/checkpoints/epoch=2-step=74195.ckpt
config_file: configs/anydoor.yaml
save_memory: False

test_dataset_names: 
  # FlickrGrounding:
  #   which_layer_text: before
  #   which_layer_image: after_reproject
  #   image_size: 512
  #   max_boxes_per_data: 10
  #   prob_use_caption: 1.0
  #   random_drop_embedding: none
  #   random_crop: False
  #   random_flip: False
  #   ref_zero: False
  
  # VGGrounding:
  #   which_layer_text: before
  #   which_layer_image: after_reproject
  #   image_size: 512
  #   max_boxes_per_data: 10
  #   prob_use_caption: 1.0
  #   random_drop_embedding: none
  #   random_crop: False
  #   random_flip: False
  #   ref_zero: False
  
  SBUGrounding:
    which_layer_text: before
    which_layer_image: after_reproject
    image_size: 512
    max_boxes_per_data: 10
    prob_use_caption: 1.0
    random_drop_embedding: none
    random_crop: False
    random_flip: False
    ref_zero: False