pretrained_model: lightning_logs/version_45/epoch=10-step=24089.ckpt
config_file: configs/anydoor.yaml
save_memory: False

test_dataset_names: 
  FlickrGrounding:
    which_layer_text: before
    which_layer_image: after_reproject
    image_size: 512
    max_boxes_per_data: 8
    prob_use_caption: 1.0
    random_drop_embedding: none
    random_crop: False
    random_flip: False